version: 2.1

orbs:
  maven: circleci/maven@0.0.12

executors:
  maven_test:
    working_directory: /testing-java-junit5

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
