version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:    
    jobs:
      working_directory: testing-java-junit5
      - maven/test # checkout, build, test, and upload test results
